<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup><ItemGroup><ProjectReference Include="..\Company.Ordering.Domain\Company.Ordering.Domain.csproj" /><ProjectReference Include="..\..\Catalog\Company.Catalog.Application\Company.Catalog.Application.csproj" /><ProjectReference Include="..\..\..\Company.Webshop.Shared\Company.Webshop.Shared.csproj" /></ItemGroup><ItemGroup><InternalsVisibleTo Include="Company.Ordering.Infrastructure" /><InternalsVisibleTo Include="UnitTests" /></ItemGroup></Project>
